### ISSUE TITLE
Dataloader对象无法读取

### ISSUE THREAD

**Issue by lx935484038** [FunkyKoki/RetinexNet_PyTorch#1]
`def train():
    decom_net.train()
    relight_net.train()

    for epoch in range(args.epoch):
        times_per_epoch, sum_loss = 0, 0.

        dataloader = torch.utils.data.DataLoader(train_set, batch_size=args.batch_size, shuffle=True,
                                                 num_workers=args.workers, pin_memory=True)
        decom_optim.param_groups[0]['lr'] = lr[epoch]
        
        for data in tqdm.tqdm(dataloader):
            print(data)`
无法从dataloader获取到data，报错如下：
`Traceback (most recent call last):
  File "train.py", line 119, in <module>
    train()
  File "train.py", line 69, in train
    for data in tqdm.tqdm(dataloader):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 187, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 173, in <listcomp>
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.`

**Comment by JiaqianLi** [comment]
I got the same problem with you and how do you solve it?

**Comment by x752155** [comment]
在utils.py中data_augmentation(image, mode)函数下面所有的
return np.(XX)
改成
return np.(XX).copy()

**Comment by weixinxu666** [comment]
> 在utils.py中data_augmentation(image, mode)函数下面所有的
> return np.(XX)
> 改成
> return np.(XX).copy()

This is the correct solution!
